steps:
  # Build the frontend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/myportfolio-frontend'
      - '--build-arg'
      - 'VITE_API_URL=$_VITE_API_URL'
      - '.'
    dir: 'frontend'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/myportfolio-frontend']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'myportfolio-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/myportfolio-frontend'
      - '--region'
      - 'us-central1' # You can change this to your preferred region
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/myportfolio-frontend'
